const letras = [
  { letra: "a", tile: "á" },
  { letra: "b" },
  { letra: "c" },
  { letra: "d" },
  { letra: "e", tile: "é" },
  { letra: "f" },
  { letra: "g" },
  { letra: "h" },
  { letra: "i", tile: "í" },
  { letra: "j" },
  { letra: "k" },
  { letra: "l" },
  { letra: "m" },
  { letra: "n" },
  { letra: "ñ" },
  { letra: "o", tile: "ó" },
  { letra: "p" },
  { letra: "q" },
  { letra: "r" },
  { letra: "s" },
  { letra: "t" },
  { letra: "u", tile: "ú" },
  { letra: "v" },
  { letra: "w" },
  { letra: "x" },
  { letra: "y" },
  { letra: "z" },
];

const palabras = [
  "dia",
  "subdirector",
  "dice",
  "ayudante",
  "casualidad",
  "usted",
  "visto",
  "alguna",
  "vez",
  "pinguino",
  "despacho",
  "director",
  "cuando",
  "llega",
  "mandado",
  "aqui",
  "nunca",
  "no",
  "despedido",
  "casa",
];

export { letras, palabras };
